version: "3.7"

services:
  app:
    image: traefik:latest
    ports: # Host mode disables inbound NAT and allows the end users source IP to be passed through.
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/data/traefik:/etc/traefik
    restart: always
    networks:
      - traefik_public
    command:
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/traefik/ext_hosts.yml"
      - "--providers.file.watch=true"
      - "--certificatesresolvers.main.acme.email=michael_calabrese@ymail.com"
      - "--certificatesresolvers.main.acme.storage=/etc/traefik/acme.json"
      # Uncomment the line to use Let's Encrypt's staging server, leave commented to use prod
      #- "--certificatesresolvers.main.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.main.acme.dnschallenge=true"
      - "--certificatesresolvers.main.acme.dnschallenge.provider=cloudflare"
    env_file:
      - stack.env
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=traefik_public"
    - "traefik.http.routers.api.rule=Host(`traefik.live.calabresemedia.com`)"
    - "traefik.http.routers.api.entrypoints=websecure"
    - "traefik.http.routers.api.tls.domains[0].main=calabresemedia.com"
    - "traefik.http.routers.api.tls.domains[0].sans=*.calabresemedia.com,*.live.calabresemedia.com"        
    - "traefik.http.routers.api.tls=true"
    - "traefik.http.routers.api.tls.certresolver=main"
    - "traefik.http.routers.api.service=api@internal"
    - "traefik.http.routers.api.middlewares=homeusers"
    - "traefik.http.middlewares.homeusers.basicauth.usersfile=/etc/traefik/.homeusers"
networks:
  traefik_public:
    external: true