version: '3.7'

services:
  db:
    image: mysql:8.0
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: wordpress
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: 'password'
    networks:
      - private

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - '16756:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - private

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    volumes: 
      - wp:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: MYSQL_USER
      WORDPRESS_DB_PASSWORD: 'password'
    networks:
      private:
      DMZ_VLAN:
        ipv4_address: 172.16.75.16

volumes:
  db:
  wp:

networks:
  private:
    driver: bridge
  DMZ_VLAN:
    external: true